<html>

<head>
	<title>Magic Mirror</title>
	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="New Clinic Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--//tags -->
	<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link href="css/appointment_style.css" rel="stylesheet" type="text/css" media="all" />
	<link href="css/font-awesome.css" rel="stylesheet">
	<!-- //for bootstrap working -->
	<link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,600,600i,700" rel="stylesheet">
</head>
    
    
    <body >


<!-- banner -->
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1" class=""></li>
			<li data-target="#myCarousel" data-slide-to="2" class=""></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
                <div style="background-image: url(images/d4.jpeg);background-size:cover;">

				<div class="container">
					<div class="carousel-caption">	
                         
                      <h3>beauty salon<br>
                        fashion for woman</h3>
						<p>IMPROVE YOUR SELFIES,SEEE YOUR STYLIST.</p>
					</div>
                    </div>
				</div>
			</div>
			<div class="item item2">
                <div style="background-image: url(images/p75.png);background-size:cover;">

				<div class="container">
					<div class="carousel-caption">
						
                  <h3>beauty salon<br>
                        fashion for woman</h3>

						<p>NOTHING MAKES A WOMEN MORE BEAUTIFUL THAN THE BELIEF SHE IS BEAUTIFUL</p>
					</div>
                    </div>
				</div>
			</div>
			<div class="item item3">
                <div style="background-image: url(images/ban4.webp);background-size:cover;">

				<div class="container">
					<div class="carousel-caption">
					
                <h3>beauty salon<br>
                        fashion for woman</h3>
						<p>LIFE ISN'T PERFECT BUT HAIR CAN BE </p>
					</div>
                    </div>
				</div>
			</div>
			
		</div>
		
        
        
       
        <!-- js -->
	<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
	<script>
		$('ul.dropdown-menu li').hover(function () {
			$(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
		}, function () {
			$(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
		});
	</script>
	<script type="text/javascript" src="js/bootstrap.js"></script>

</body>

</html>